# Generated by Django 3.2.2 on 2021-05-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_item_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pic',
            field=models.CharField(default='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.dribbble.com%2Fusers%2F448879%2Fscreenshots%2F2487655%2Faguacate.jpg&f=1&nofb=1', max_length=100),
        ),
    ]
